// src/components/Box.tsx
import type { ReactNode } from "react";

export type BoxType =
  | "indent"
  | "panel-d-1"
  | "panel-d-2"
  | "indent"
  | "textarea"
  | "border-groove";

export interface BoxProps extends React.HTMLAttributes<HTMLDivElement> {
  type: BoxType;
  extraStyles?: React.CSSProperties;
  children?: ReactNode | ReactNode[];
  extraClass?: string;
}

export function Box({
  type,
  extraStyles,
  extraClass,
  children,
  ...rest
}: BoxProps) {
  return (
    <div
      {...rest}
      className={`border-9-base ${extraClass ?? ""}`}
      style={
        {
          "--img": `url(/public/win-55-ui/${type}.png)`,
          ...extraStyles,
        } as React.CSSProperties
      }
    >
      {children}
    </div>
  );
}

// src/components/Box.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'
import { computed, ref } from 'vue'

export type BoxType =
  | 'indent'
  | 'panel-d-1'
  | 'panel-d-2'
  | 'textarea'
  | 'border-groove'

const props = defineProps<{
  type: BoxType
  extraStyles?: CSSProperties
  extraClass?: string
}>()

const rootRef = ref<HTMLDivElement | null>(null)

const style = computed<CSSProperties>(() => ({
  '--img': `url(/win-55-ui/${props.type}.png)`,
  ...props.extraStyles,
} as CSSProperties))

defineExpose({ el: rootRef })
</script>

<template>
  <div
    ref="rootRef"
    :class="['border-9-base', extraClass ?? '']"
    :style="style"
  >
    <slot />
  </div>
</template>
