// src/components/MenuDropdown.vue
<script setup lang="ts">
import BaseDropdown from './BaseDropdown.vue'
import Box from './Box.vue'
</script>

<template>
  <BaseDropdown>
    <template #trigger>
      <slot name="trigger" />
    </template>
    <template #items>
      <Box type="panel-d-1">
        <slot name="items" />
      </Box>
    </template>
  </BaseDropdown>
</template>

// src/components/MenuDropdown.tsx
import type { ReactElement, ReactNode } from "react";
import { BaseDropdown } from "./BaseDropdown";
import { Box } from "./Box";

interface DropdownProps {
  trigger: ReactElement<{ onClick?: React.MouseEventHandler<unknown> }>;
  items: ReactNode[];
}

export function MenuDropdown({trigger, items}: DropdownProps) {
  return <BaseDropdown 
    items={items}
    trigger={trigger}
    itemWrapper={ (items) =>
      <Box type="panel-d-1">
        {items}
      </Box>
    }
  />
}
