// src/components/Typography.tsx
import React from "react"
import { typographyStyles, type TypographySettings } from "../helpers/typography"

interface TypographyComponentProps {
  element?: keyof HTMLElementTagNameMap
  children?: React.ReactNode
}

export function Typography(props: TypographySettings & TypographyComponentProps) {
  const { children, ...restProps } = props
  const tag = restProps.element ?? 'span'
  const styles = typographyStyles(restProps)

  if (!restProps.element) {
    styles.display = 'contents'
  }

  return React.createElement(tag, { style: styles }, children)
}

// src/components/Typography.vue
<script setup lang="ts">
import { computed } from 'vue'
import { typographyStyles, type TypographySettings } from '../helpers/typography'

interface Props extends TypographySettings {
  element?: string
}

const props = withDefaults(defineProps<Props>(), {
  element: undefined,
})

const tag = computed(() => props.element ?? 'span')

const styles = computed(() => {
  const s = typographyStyles(props)
  if (!props.element) {
    s.display = 'contents'
  }
  return s
})
</script>

<template>
  <component :is="tag" :style="styles">
    <slot />
  </component>
</template>
