// src/App.tsx
import './App.css'
import { Box } from './components/Box'
import Titlebar from './components/Titlebar';
import { Button } from './components/Button';
import { BaseDropdown } from './components/BaseDropdown';
import { useSineWave } from './helpers/useSineWave';
import { BaseInput } from './components/BaseInput';
import { useState } from 'react';
import { Typography } from './components/Typography';
import Checkbox from './components/Checkbox';
import RadioButton from './components/RadioButton';
import { MenuDropdown } from './components/MenuDropdown';
import { HDivider } from './components/HDivider';



function App() {

  const {values} = useSineWave(6)
  
  const containerStyle = {
    width: 'fit-content',
    margin: '4px',
    padding: '4px'
  }

  const boxStyle = {
    width: 2*48+48,
    height: 2*24+48,
    marginBottom: 10,
    marginLeft: 8,
  }

  const windowStyle = {
    width: 3*48+160,
    height: 3*24+48,
    marginBottom: 10,
    marginLeft: 8
  }

  const [exampleTextInputState, setExampleTextInputState] = useState('oleg')
  const [exampleCheckboxState, setExampleCheckboxState] = useState(false)
  const [exampleRadioState, setExampleRadioState] = useState('oleg')

  return (
    <Typography fontColor='black'>
      <h1>Kitchen sink</h1>
      <div>
        <h2>The quick brown fox jumps over the lazy dog</h2>
        <h2>ABCDE</h2>
      </div>
      <Box type='border-groove' extraStyles={containerStyle}>
        <h2>Text input</h2>
        <Typography fontShadowColor='#00000000'>
          <BaseInput value={exampleTextInputState} onChange={setExampleTextInputState} extraStyles={{width: '512px'}}/>
        </Typography>
      </Box>

      <Box type='panel-d-2' extraStyles={containerStyle}>
        <h2>Form elements</h2>
        <Box type='border-groove' extraStyles={containerStyle}>
          <Checkbox checked={exampleCheckboxState} onChange={setExampleCheckboxState} label='Oleg' />
          <Checkbox checked={exampleCheckboxState} onChange={setExampleCheckboxState} label='Oleg' />
        </Box>
        <Box type='border-groove' extraStyles={containerStyle}>
          <RadioButton value='a' target={exampleRadioState} onChange={setExampleRadioState} label='A' />
          <RadioButton value='oleg' target={exampleRadioState} onChange={setExampleRadioState} label='Oleg' />
          <RadioButton value='b' target={exampleRadioState} onChange={setExampleRadioState} label='B' />
          <RadioButton value='c' target={exampleRadioState} onChange={setExampleRadioState} label='C' />
        </Box>
      </Box>

      <Box type='border-groove' extraStyles={containerStyle}>
        <h2>
          Sized boxes
        </h2>
        <Box extraStyles={{...boxStyle, width: 2*48+values[0].cos*50, height: 2*24+values[0].sin*30}} type='panel-d-1'></Box> <br />
        <Box extraStyles={{...boxStyle, width: 2*48+values[1].cos*50, height: 2*24+values[1].sin*30}} type='panel-d-2'></Box> <br />
        <Box extraStyles={{...boxStyle, width: 2*48+values[2].cos*50, height: 2*24+values[2].sin*30}} type='border-groove'></Box> <br />
        <Box extraStyles={{...boxStyle, width: 2*48+values[3].cos*50, height: 2*24+values[3].sin*30}} type='indent'></Box> <br />
        <Box extraStyles={{...boxStyle, width: 2*48+values[4].cos*50, height: 2*24+values[4].sin*30}} type='textarea'></Box> <br />
      </Box>

      <div>
        <h2>
          Window
        </h2>
        <Box extraStyles={{...windowStyle, width: 2*48+values[5].cos*30+150, height: 2*24+values[5].sin*30+150}} type='panel-d-2'>
          <Titlebar title='Oleg' icon='/win-55-ui/icons/program.png' />
        </Box>
      </div>
      
      <Button extraStyles={{margin: '8px'}} onClick={() => alert('Click!')}>
        Oleg
      </Button>

      <div>
        <h2>Basic dropdown</h2>
        <div style={{marginLeft: '8px'}}>
          <BaseDropdown 
            trigger={<Button>This is a dropdown</Button>}
            items={[
              <Button>Item 1</Button>,
              <Button>Item 2</Button>,
              <Button>Item 3</Button>,
              <Button>Item 4</Button>,
            ]}
          />
          <MenuDropdown 
            trigger={<Button>This is a nice menu dropdown!</Button>}
            items={[
              <div>New</div>,
              <div>Open...</div>,
              <HDivider />,
              <div>Save</div>,
              <div>Save as...</div>,
            ]}
          />
          <br />
          <br />
          <br />
          <br />
          <br />
          <BaseDropdown 
            trigger={<Button>This is also a dropdown</Button>}
            items={[
              <Button>Item 1</Button>,
              <Button>Item 2</Button>,
              <Button>Item 3</Button>,
              <Button>Item 4</Button>,
            ]}
          />
        </div>
      </div>
    </Typography>
  )
}

export default App

// src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import Box from './components/Box.vue'
import Button from './components/Button.vue'
import BaseDropdown from './components/BaseDropdown.vue'
import { useSineWave } from './helpers/useSineWave'
import BaseInput from './components/BaseInput.vue'
import Typography from './components/Typography.vue'
import Checkbox from './components/Checkbox.vue'
import RadioButton from './components/RadioButton.vue'
import MenuDropdown from './components/MenuDropdown.vue'
import HDivider from './components/HDivider.vue'
import Window from './components/Window.vue'
import Tooltip from './components/Tooltip.vue'
import Balloon from './components/Balloon.vue'

const { values } = useSineWave(5)

const containerStyle = {
  width: 'fit-content',
  margin: '4px',
  padding: '4px',
}

const boxStyle = {
  marginBottom: '10px',
  marginLeft: '8px',
}

const windowStyle = {
  marginBottom: '10px',
  marginLeft: '8px',
}

const handleClick = () => window.alert('Click!')

const exampleTextInputState = ref('oleg')
const exampleCheckboxState = ref(false)
const exampleRadioState = ref('oleg')
</script>

<template>
  <Typography font-color="black">
    <h1>Kitchen sink</h1>
    <div>
      <h2>The quick brown fox jumps over the lazy dog</h2>
      <h2>ABCDE</h2>
    </div>
    <Box type="border-groove" :extra-styles="containerStyle">
      <h2>Text input</h2>
      <Typography font-shadow-color="#00000000">
        <BaseInput
          v-model="exampleTextInputState"
          :extra-styles="{ width: '512px' }"
        />
      </Typography>
    </Box>

    <Box type="panel-d-2" :extra-styles="containerStyle">
      <h2>Form elements</h2>
      <Box type="border-groove" :extra-styles="containerStyle">
        <Checkbox
          v-model="exampleCheckboxState"
          label="Oleg"
        />
        <Checkbox
          v-model="exampleCheckboxState"
          label="Oleg"
        />
      </Box>
      <Box type="border-groove" :extra-styles="containerStyle">
        <RadioButton
          v-model="exampleRadioState"
          value="a"
          label="A"
        />
        <RadioButton
          v-model="exampleRadioState"
          value="oleg"
          label="Oleg"
        />
        <RadioButton
          v-model="exampleRadioState"
          value="b"
          label="B"
        />
        <RadioButton
          v-model="exampleRadioState"
          value="c"
          label="C"
        />
      </Box>
    </Box>

    <Box type="border-groove" :extra-styles="containerStyle">
      <h2>Sized boxes</h2>
      <Box
        :extra-styles="{ ...boxStyle, width: (2 * 48 + values[0].cos * 50) + 'px', height: (2 * 24 + values[0].sin * 30) + 'px' }"
        type="panel-d-1"
      />
      <br />
      <Box
        :extra-styles="{ ...boxStyle, width: (2 * 48 + values[1].cos * 50) + 'px', height: (2 * 24 + values[1].sin * 30) + 'px' }"
        type="panel-d-2"
      />
      <br />
      <Box
        :extra-styles="{ ...boxStyle, width: (2 * 48 + values[2].cos * 50) + 'px', height: (2 * 24 + values[2].sin * 30) + 'px' }"
        type="border-groove"
      />
      <br />
      <Box
        :extra-styles="{ ...boxStyle, width: (2 * 48 + values[3].cos * 50) + 'px', height: (2 * 24 + values[3].sin * 30) + 'px' }"
        type="indent"
      />
      <br />
      <Box
        :extra-styles="{ ...boxStyle, width: (2 * 48 + values[4].cos * 50) + 'px', height: (2 * 24 + values[4].sin * 30) + 'px' }"
        type="textarea"
      />
      <br />
    </Box>

    <div>
      <h2>Window</h2>
      (it's floating)
      <Window resizable :extra-styles="{ ...windowStyle }">
        Oleg
      </Window>
    </div>

    <div>
      <h2>Button with tooltip</h2>
      <Tooltip text="oleg">
        <Button :extra-styles="{ margin: '8px' }" @click="handleClick">
          Oleg
        </Button>
      </Tooltip>
      
    </div>

    <div style=" 
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 100px;"
    >
      <Balloon side="top" text="TOP" :shown="true">
        <Button>TOP</Button>
      </Balloon>
      <Balloon side="left" text="LEFT" :shown="true">
        <Button>LEFT</Button>
      </Balloon>
      <Balloon side="right" text="RIGHT" :shown="true">
        <Button>RIGHT</Button>
      </Balloon>
      <Balloon side="bottom" text="BOTTOM" :shown="true">
        <Button>BOTTOM</Button>
      </Balloon>

      <Balloon side="top" bias="right" :shown="true">
        <Button>TOP</Button>
        <template #content>
          TEXT TEXT TEXT TEXT  <br>
          TEXT TEXT TEXT TEXT 
        </template>
      </Balloon>
      <Balloon side="left" bias="down" text="LEFT" :shown="true">
        <Button>LEFT</Button>
        <template #content>
          TEXT TEXT TEXT TEXT <br>
          TEXT TEXT TEXT TEXT <br>
          TEXT TEXT TEXT TEXT <br>
          TEXT TEXT TEXT TEXT  
        </template>
      </Balloon>
      <Balloon side="right" bias="up" text="RIGHT" :shown="true">
        <Button>RIGHT</Button>
        <template #content>
          TEXT TEXT TEXT TEXT <br>
          TEXT TEXT TEXT TEXT <br>
          TEXT TEXT TEXT TEXT <br>
          TEXT TEXT TEXT TEXT  
        </template>
      </Balloon>
      <Balloon side="bottom" bias="left" :shown="true">
        <Button>BOTTOM</Button>
        <template #content>
          TEXT TEXT TEXT TEXT  <br>
          TEXT TEXT TEXT TEXT 
        </template>
      </Balloon>
    </div>

    <div>
      <h2>Basic dropdown</h2>
      <div style="margin-left: 8px">
        <BaseDropdown>
          <template #trigger>
            <Button>This is a dropdown</Button>
          </template>
          <template #items>
            <Button>Item 1</Button>
            <Button>Item 2</Button>
            <Button>Item 3</Button>
            <Button>Item 4</Button>
          </template>
        </BaseDropdown>
        <MenuDropdown>
          <template #trigger>
            <Button>This is a nice menu dropdown!</Button>
          </template>
          <template #items>
            <div>New</div>
            <div>Open...</div>
            <HDivider />
            <div>Save</div>
            <div>Save as...</div>
          </template>
        </MenuDropdown>
        <br />
        <br />
        <br />
        <br />
        <br />
        <BaseDropdown>
          <template #trigger>
            <Button>This is also a dropdown</Button>
          </template>
          <template #items>
            <Button>Item 1</Button>
            <Button>Item 2</Button>
            <Button>Item 3</Button>
            <Button>Item 4</Button>
          </template>
        </BaseDropdown>
      </div>
    </div>
  </Typography>
</template>
